[package]
name = "simple-kv"
version = "0.1.0"
authors = ["syj <Sunyuejun_7@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#grpcio = "0.6"
#protobuf = { version = "2.0", optional = true }